import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AiportService {

  constructor() { }
formData = new BehaviorSubject<any[]>([])
 formArrayData = new BehaviorSubject<any[]>([])

airport:any=[
{arrival: 'Indira Gandhi International Airport, New Delhi DEL', departure: 'Chhatrapati Shivaji International Airport, Mumbai BOM', time:'2.25', distance:'1138.18'},
{arrival: 'Indira Gandhi International Airport, New Delhi DEL', departure: '	Chennai International Airport, Chennai MAA', time:'2.93', distance:'	1760.78'},
{arrival: 'Chhatrapati Shivaji International Airport, Mumbai BOM', departure: 'Chennai International Airport, Chennai MAA',  time:'2.13', distance:'1033.36'},
{arrival: 'Indira Gandhi International Airport, New Delhi DEL',departure:'Kempegowda International Airport, Bangalore BLR',  time:'	2.87', distance:'	1709.97'},
{arrival: 'Indira Gandhi International Airport, New Delhi DEL', departure: 'Netaji Subhash Chandra Bose International Airport, Kolkata CCU',  time:'1312.62', distance:'	2.44'},
{arrival: 'Chhatrapati Shivaji International Airport, Mumbai BOM', departure: 'Netaji Subhash Chandra Bose International Airport, Kolkata CCU',  time:'2.83', distance:'1665.41'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM', departure:'Kempegowda International Airport, Bangalore BLR', distance:	'834.12',  time:	'1.91'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Rajiv Gandhi International Airport, Hyderabad HYD', distance:	'1267.62',  time:	'2.39'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Rajiv Gandhi International Airport, Hyderabad HYD', distance:	'622.81',  time:'1.68'},
{arrival:'Chennai International Airport, Chennai MAA'	, departure:'Kempegowda International Airport, Bangalore BLR', distance:	'267.74',  time:	'1.29'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Cochin International Airport, Kochi COK', distance:	'1063.76',  time:	'2.17'},
{arrival:'Chennai International Airport, Chennai MAA', departure:	'Rajiv Gandhi International Airport, Hyderabad HYD'	, distance:'507.19',  time:	'1.56'},
{arrival:'Kempegowda International Airport, Bangalore BLR	', departure:'Rajiv Gandhi International Airport, Hyderabad HYD', distance:	'455.14',  time:	'1.5'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:	'Rajiv Gandhi International Airport, , distance:Hyderabad HYD', distance:	'1207.61'	,  time:'2.32'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM', departure:'	Trivandrum International Airport, Thiruvananthapuram TRV', distance:	'1257.65',  time:	'2.38'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:	'756.48',  time:'	1.83'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Pune Airport, Pune PNQ'	, distance:'1156.41',  time:'	2.27'},
{arrival:'Chennai International Airport, Chennai MAA', departure:'	Cochin International Airport, Kochi COK', distance:	'517.64',  time:	'1.57'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Cochin International Airport, Kochi COK', distance:	'367.24',  time:	'1.4'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:'	444.14',  time:	'1.49'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Lokpriya Gopinath Bordoloi International Airport, Guwahati GAU', distance:	'1455.44',  time:	'2.6'},
{arrival:'Rajiv Gandhi International Airport, Hyderabad HYD'	, departure:'Cochin International Airport, Kochi COK	', distance:'817.02'	,  time:'1.9'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Dabolim Airport, Vasco da Gama GOI', distance:	'424.78'	,  time:'1.47'},
{arrival:'Chennai International Airport, Chennai MAA', departure:'	Trivandrum International Airport, Thiruvananthapuram TRV', distance:	'614.13',  time:	'1.67'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:	'Trivandrum International Airport, Thiruvananthapuram TRV', distance:	'531.32',  time:'	1.58'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Chaudhary Charan Singh International Airport, Lucknow LKO'	, distance:'423.45'	,  time:'1.46'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL'	, departure:'Vishakhapatnam Airport, Visakhapatnam VTZ', distance:	'1357.93'	,  time:'2.49'},
{arrival:'Chennai International Airport, Chennai MAA'	, departure:'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:	'1374.88',  time:	'2.51'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Jaipur International Airport, Jaipur JAI'	, distance:'231.69'	,  time:'1.25'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Coimbatore International Airport, Coimbatore CJB', distance:	'1949.89	',  time:'3.14'},
{arrival:'Chennai International Airport, Chennai MAA', departure:'	Pune Airport, Pune PNQ', distance:	'912.84',  time:'	2'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:	'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:	'1619.86',  time:	'2.78'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:'	Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:	'1221.83	',  time:'2.34'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Bagdogra Airport, Siliguri IXB', distance:	'1125.11	',  time:'2.23'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Devi Ahilyabai Holkar Airport, Indore IDR	', distance:'662.83',  time:	'1.73'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Chaudhary Charan Singh International Airport, Lucknow LKO', distance:	'1183.53',  time:'	2.3'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Vishakhapatnam Airport, Visakhapatnam VTZ', distance:	'1102.99'	,  time:'2.21'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Pune Airport, Pune PNQ', distance:	'722.65',  time:	'1.79'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:	'Pune Airport, Pune PNQ', distance:	'1577.23'	,  time:'2.73'},
{arrival:'Chennai International Airport, Chennai MAA'	, departure:'Calicut International Airport, Calicut CCJ', distance:	'502.38',  time:	'1.55'},
{arrival:'Cochin International Airport, Kochi COK', departure:	'Trivandrum International Airport, Thiruvananthapuram TRV', distance:	'194.18'	,  time:'1.21'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Dr. Babasaheb Ambedkar International Airport, Naqpur NAG', distance:	'853.85'	,  time:'1.94'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Coimbatore International Airport, Coimbatore CJB', distance:	',  time:1001.74'	,  time:'2.1'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure: 'International Airport, Jaipur JAI', distance:	'911.28',  time:	'2'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:'	Calicut International Airport, Calicut CCJ'	, distance:'297.89	',  time:'1.33'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:	'Lokpriya Gopinath Bordoloi International Airport, Guwahati GAU', distance:'	498.29'	,  time:'1.55'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:	'Lokpriya Gopinath Bordoloi International Airport, Guwahati GAU', distance:	'2039.29'	,  time:'3.23'},
{arrival:'Chennai International Airport, Chennai MAA'	, departure:'Dabolim Airport, Vasco da Gama GOI', distance:	'733.04',  time:'	1.8'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Sheikh ul Alam Airport, Srinagar SXR', distance:'	642'	,  time:'1.7'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Devi Ahilyabai Holkar Airport, Indore IDR	', distance:'505.93'	,  time:'1.55'},
{arrival:'Rajiv Gandhi International Airport, Hyderabad HYD', departure:	'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', distance:'	887.65',  time:	'1.97'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Dabolim Airport, Vasco da Gama GOI', distance:	'482.91'	,  time:'1.53'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Dr. Babasaheb Ambedkar International Airport, Naqpur NAG', distance:	'682.56'	,  time:'1.75'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM	', departure:'Mangalore International Airport, Mangalore IXE', distance:	'714.72',  time:	'1.78'},
{arrival:'Rajiv Gandhi International Airport, Hyderabad HYD'	, departure:'Pune Airport, Pune PNQ', distance:	'500.24',  time:'	1.55'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Sheikh ul Alam Airport, Srinagar SXR', distance:	'1667.26'	,  time:'2.83'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Lok Nayak Jayaprakash Airport, Patna PAT', distance:	'856.67',  time:	'1.94'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL'	, departure:'Jammu Airport, Jammu IXJ', distance:	'507.02',  time:	'1.56'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Raipur Airport, Raipur RPR', distance:	'944.79',  time:	'2.04'},
{arrival:'Cochin International Airport, Kochi COK	', departure:'Pune Airport, Pune PNQ'	, distance:'974.65',  time:	'2.07'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Birsa Munda Airport, Ranchi IXR', distance:	'1007.62'	,  time:'2.1'},
{arrival:'Rajiv Gandhi International Airport, Hyderabad HYD'	, departure:'Dabolim Airport, Vasco da Gama GOI', distance:'	532.09',  time:	'1.58'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM', departure:	'Jammu Airport, Jammu IXJ',distance:	'1524.9'	,  time:'2.67'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM', departure:	'Raipur Airport, Raipur RPR',distance:	'954.65'	,  time:'2.05'},
{arrival:'Cochin International Airport, Kochi COK'	, departure:'Calicut International Airport, Calicut CCJ',distance:	'119.88'	,  time:'1.13'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Lal Bahadur Shastri Airport, Varanasi VNS',distance:	'666.97',  time:'	1.73'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Sri Guru Ram Dass Jee International Airport, Amritsar ATQ',distance:'	413.85'	,  time:'1.45'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Biju Patnaik Airport, Bhubaneswar BBI',distance:	'1277.65'	,  time:'2.4'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:'	Chandigarh Airport, Chandigarh IXC'	,distance:'236.24',  time:'	1.26'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Lal Bahadur Shastri Airport, Varanasi VNS',distance:	'1247.23	',  time:'2.37'},
{arrival:'Chennai International Airport, Chennai MAA', departure:'	Vishakhapatnam Airport, Visakhapatnam VTZ	',distance:'619.65',  time:	'1.68'},
{arrival:'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', departure:	'Pune Airport, Pune PNQ'	,distance:'517.33',  time:'	1.57'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Sri Guru Ram Dass Jee International Airport, Amritsar ATQ',distance:	'1416.54'	,  time:'2.55'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Biju Patnaik Airport, Bhubaneswar BBI'	,distance:'1361.62'	,  time:'2.49'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM'	, departure:'Chandigarh Airport,Chandigarh IXC' , distance:'1347.12', time:'2.48'},
{arrival:'Chennai International Airport, Chennai MAA', departure:	'Coimbatore International Airport, Coimbatore CJB',distance:'	403.8',  time:	'1.44'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:'	Vishakhapatnam Airport, Visakhapatnam VTZ',distance:'	773.07'	,  time:'1.85'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:	'Chaudhary Charan Singh International Airport, Lucknow LKO',distance:	'1544.04'	,  time:'2.69'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Vishakhapatnam Airport, Visakhapatnam VTZ'	,distance:'776.16',  time:'	1.85'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Coimbatore International Airport, Coimbatore CJB',distance:'	251.59'	,  time:'1.28'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:'	Jaipur International Airport, Jaipur JAI',distance:'	1356.65',  time:'	2.49'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Jaipur International Airport, Jaipur JAI',distance:	'1527.89'	,  time:'2.67'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Maharana Pratap Airport, Udaipur UDR',distance:	'542.57',  time:	'1.59'},
{arrival:'Sardar Vallabhbhai Patel International Airport, Ahmedabad AMD', departure:	'Dabolim Airport, Vasco da Gama GOI',distance:	'864.91',  time:'	1.95'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:'	Bagdogra Airport, Siliguri IXB',distance:'	447.86'	,  time:'1.49'},
{arrival:'Kempegowda International Airport, Bangalore BLR', departure:	'Devi Ahilyabai Holkar Airport, Indore IDR'	,distance:'1077.9'	,  time:'2.18'},
{arrival:'Pune Airport, Pune PNQ', departure:'	Dabolim Airport, Vasco da Gama GOI',distance:	'356.07',  time:	'1.39'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Dr. Babasaheb Ambedkar International Airport, Naqpur NAG',distance:	'889.23',  time:'	1.97'},
{arrival:'Kempegowda International Airport, Bangalore BLR'	, departure:'Mangalore International Airport, Mangalore IXE',distance:	'306.14',  time:	'1.34'},
{arrival:'Netaji Subhash Chandra Bose International Airport, Kolkata CCU', departure:	'Dr. Babasaheb Ambedkar International Airport, Naqpur NAG',distance:'	985.13'	,  time:'2.08'},
{arrival:'Rajiv Gandhi International Airport, Hyderabad HYD'	, departure:'Vishakhapatnam Airport, Visakhapatnam VTZ',distance:	'511.4	',  time:'1.56'},
{arrival:'Chhatrapati Shivaji International Airport, Mumbai BOM', departure:'	Maharana Pratap Airport, Udaipur UDR',distance:'	623.85'	,  time:'1.68'},
{arrival:'Indira Gandhi International Airport, New Delhi DEL', departure:	'Raja Bhoj International Airport, Bhopal BHO',distance:	'587.44'	,  time:'1.64'},
]
 
plane:any=[{PlaneName:'Embraer ERJ-135LR',Seat :'37 Seater',Base:' New Delhi'},
{PlaneName:'Embraer ERJ-135LR',Seat :'37 Seater',Base:' New Delhi'},
{PlaneName:'Cessna Caravan',Seat :'7 Seater',Base:'  Indore'},
{PlaneName:'Piaggio Avanti',Seat :'6 Seater',Base:' New Delhi'},
{PlaneName:'Cessna Citation 525A',Seat :'7 Seater ',Base:' New Delhi'},
{PlaneName:'Hawker Beechcraft 750',Seat :'8 Seater',Base:' New Delhi'},
{PlaneName:'Hawker Beechcraft 800XP',Seat :'8 Seater',Base:'Pune'},
{PlaneName:'Challenger 604',Seat :'11 Seater',Base:'Mumbai'},
{PlaneName:'Bombardier Challenger 850',Seat :'14 Seater',Base:' Pune'},
{PlaneName:'Falcon 2000 Easy',Seat :'8 Seater ',Base:' Bangalore'},
{PlaneName:'Falcon 2000',Seat :'9 Seater ',Base:' Bangalore'},
{PlaneName:'Global 6000',Seat :'8 Seater ',Base:' Bangalore'},
{PlaneName:'Falcon 2000 Easy',Seat :'14 Seater  ',Base:'Mumbai'},
{PlaneName:'Bell 412',Seat :'8 Seater ',Base:' Bangalore'},
{PlaneName:'Agusta A109',Seat :'5 Seater ',Base:' Vijayawada'},
{PlaneName:'Eurocopter Ecureuil',Seat :'5 Seater',Base:' Mumbai'},
]

}

